language: java
sudo: false
install: true

jdk:
  - oraclejdk11
  - openjdk11

addons:
  sonarcloud:
    organization: "benslabbert-github"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
