language: java

jdk:
  - openjdk11

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -Dmaven.test.failure.ignore=false
  - mvn clean install sonar:sonar -Dsonar.projectKey=BenSlabbert_trak -Dsonar.organization=benslabbert-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
  - mvn dockerfile:push -f api/pom.xml
  - mvn dockerfile:push -f engine/pom.xml
  - mvn dockerfile:push -f worker/pom.xml
  - mvn dockerfile:push -f search/pom.xml
