version: '2.4'

services:

  rabbit:
    image: rabbitmq:3.7.14-management-alpine
    hostname: rabbit
    restart: on-failure
    mem_limit: 600m
    environment:
      - RABBITMQ_DEFAULT_USER=trak
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbit-data:/var/lib/rabbitmq

  redis:
    image: redis:5.0.4-alpine
    restart: on-failure
    ports:
      - 6379:6379
    mem_limit: 600m
    volumes:
      - redis-data:/data

  rds:
    image: mariadb:10.3.14
    restart: on-failure
    ports:
      - 3306:3306
    volumes:
      - rds-data:/var/lib/mysql
    mem_limit: 600m
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=trak
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

  engine:
    build: engine/
    image: benjaminslabbert/trak_engine:1.0.2
    restart: on-failure
    mem_limit: 600m
    environment:
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - rds
      - rabbit

  worker:
    build: worker/
    image: benjaminslabbert/trak_worker:1.0.2
    restart: on-failure
    mem_limit: 600m
    environment:
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - rds
      - rabbit
      - engine

  search:
    build: search/
    image: benjaminslabbert/trak_search:1.0.2
    restart: on-failure
    mem_limit: 250m
    ports:
      - 8081:8081
      - 50052:50052
    environment:
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - rds
      - rabbit
      - es

  api:
    build: api/
    image: benjaminslabbert/trak_api:1.0.2
    restart: on-failure
    mem_limit: 250m
    ports:
      - 8082:8082
      - 50051:50051
    environment:
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - rds
      - rabbit

  ui:
    image: benjaminslabbert/trak_ui:1.0.2
    ports:
      - 3000:3000
    mem_limit: 250m
    depends_on:
      - search
      - api

# change to overlay2 driver
volumes:
  rabbit-data:
    driver: local
  rds-data:
    driver: local
  redis-data:
    driver: local
