version: '2.2'

services:

  rabbit:
    image: rabbitmq
    hostname: rabbit
    restart: always
    mem_limit: 600m
    ports:
      - 5672:5672
    volumes:
      - rabbit-data:/var/lib/rabbitmq

  redis:
    image: redis:5-alpine
    restart: always
    ports:
      - 6379:6379
    mem_limit: 600m
    volumes:
      - redis-data:/data

  rds:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - rds-data:/var/lib/mysql
    mem_limit: 600m
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=trak
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

  engine:
    build: engine/
    image: benjaminslabbert/trak_engine:1.0.0
    restart: always
    mem_limit: 600m
    environment:
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - rds
      - rabbit

  worker:
    build: worker/
    image: benjaminslabbert/trak_worker:1.0.0
    restart: always
    mem_limit: 600m
    environment:
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - rds
      - rabbit
      - engine

  search:
    build: search/
    image: benjaminslabbert/trak_search:1.0.0
    restart: always
    mem_limit: 250m
    ports:
      - 8081:8080
      - 50052:50052
    environment:
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - rds
      - rabbit
      - es

  api:
    build: api/
    image: benjaminslabbert/trak_api:1.0.0
    restart: always
    mem_limit: 250m
    ports:
      - 8082:8080
      - 50051:50051
    environment:
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - rds
      - rabbit

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=es"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data

  es-slave-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=es"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data-slave-1:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.1
    restart: always
    ports:
      - 5601:5601
    volumes:
      - kibana-data:/usr/share/kibana
    environment:
      SERVER_NAME: kibana.local
      ELASTICSEARCH_URL: http://es:9200
    depends_on:
      - es

  logstash:
    build: ./logstash-conf/
    image: benjaminslabbert/trak_logstash:1.0.0
    ports:
      - 9600:9600
    restart: always
    depends_on:
      - es

  ui:
    image: benjaminslabbert/trak_ui:1.0.0
    ports:
      - 3000:3000
    mem_limit: 250m
    depends_on:
      - search
      - api

# change to overlay2 driver
volumes:
  rabbit-data:
    driver: local
  rds-data:
    driver: local
  es-data:
    driver: local
  es-data-slave-1:
    driver: local
  kibana-data:
    driver: local
  redis-data:
    driver: local
