version: '3.3'

services:

  rabbit:
    image: rabbitmq
    hostname: rabbit
    restart: always
    volumes:
      - "./.data/rabbit:/var/lib/rabbitmq"

  rds:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=trak
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - "./.data/db_mysql:/var/lib/mysql"
    ports:
      - 3306:3306
