version: '2.4'

services:

  rabbit:
    image: rabbitmq
    hostname: rabbit
    restart: always
    mem_limit: 300m
    ports:
      - 5672:5672
    volumes:
      - rabbit-data:/var/lib/rabbitmq

  redis:
    image: redis:5-alpine
    restart: always
    ports:
      - 6379:6379
    mem_limit: 300m
    volumes:
      - redis-data:/data

  rds:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - rds-data:/var/lib/mysql
    mem_limit: 300m
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=trak
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.1
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - es-data:/usr/share/elasticsearch/data
    mem_limit: 1024m
    environment:
      - "discovery.type=single-node"
      - "transport.host=es"

  #  kibana:
  #    image: docker.elastic.co/kibana/kibana:6.4.1
  #    restart: always
  #    ports:
  #      - 5601:5601
  #    volumes:
  #      - "kibana-data:/usr/share/kibana"
  #    environment:
  #      SERVER_NAME: kibana.local
  #      ELASTICSEARCH_URL: http://es:9200
  #    depends_on:
  #      - es

  logstash:
    build: ./logstash-conf-local/
    image: benjaminslabbert/trak_logstash_local:0.0.0
    network_mode: "host"
    ports:
      - 9600:9600
    restart: always
    mem_limit: 1024m
    depends_on:
      - es

  ui:
    image: benjaminslabbert/trak_ui:1.0.0
    ports:
      - 3000:3000
    mem_limit: 250m

volumes:
  rabbit-data:
    driver: local
  rds-data:
    driver: local
  es-data:
    driver: local
  kibana-data:
    driver: local
  redis-data:
    driver: local
