version: '3.7'

services:

  #  phpadmin:
  #    image: phpmyadmin/phpmyadmin:4.8.5
  #    ports:
  #      - 8080:80
  #    environment:
  #      - "PMA_USER=user"
  #      - "PMA_PASSWORD=password"
  #      - "PMA_HOST=rds"

  portainer:
    image: portainer/portainer:1.22.1
    ports:
      - 9000:9000
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "admin-password=admin123"

  rabbit:
    image: rabbitmq:3.7.14-management-alpine
    hostname: rabbit
    restart: on-failure
    environment:
      - RABBITMQ_DEFAULT_USER=trak
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbit-data:/var/lib/rabbitmq

  redis:
    image: redis:5.0.4-alpine
    command: redis-server --requirepass password
    restart: on-failure
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  rds:
    image: mariadb:10.3.14
    restart: on-failure
    ports:
      - 3306:3306
    volumes:
      - rds-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=trak
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

  sonic:
    image: valeriansaliou/sonic:v1.2.3
    ports:
      - 1491:1491
    volumes:
      - ./sonic/sonic.cfg:/etc/sonic.cfg

  ui:
    image: benjaminslabbert/trak_ui:1.0.2
    ports:
      - 3000:3000

volumes:
  rabbit-data:
    driver: local
  rds-data:
    driver: local
  redis-data:
    driver: local
