server:
  port: ${TOMCAT_PORT:8082}
spring:
  config:
    name: trak-worker
  liquibase:
    change-log: classpath:liquibase.sql
  jpa:
    show-sql: false
  rabbitmq:
    username: trak
    password: password
    host: localhost
    virtual-host: /
    port: 5672
    listener:
      simple:
        concurrency: 2
        max-concurrency: 4
        retry:
          max-attempts: 3
          enabled: true
          max-interval: 10000ms
  redis:
    host: localhost
    port: 6379
    ssl: false
    password: password
  datasource:
    url: jdbc:mysql://localhost/trak
    username: user
    password: password

management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus
