server:
  port: ${TOMCAT_PORT:8080}
spring:
  config:
    name: trak-api
  liquibase:
    change-log: classpath:liquibase.sql
  jpa:
    show-sql: false
  rabbitmq:
    username: ${RABBIT_MQ_USERNAME:trak}
    password: ${RABBIT_MQ_PASSWORD:password}
    host: ${RABBIT_MQ_HOST:rabbit}
    virtual-host: ${RABBIT_MQ_VIRTUAL_HOST:/}
    port: ${RABBIT_MQ_PORT:5672}
    listener:
      simple:
        concurrency: ${RABBIT_MQ_CONCURRENCY:2}
        max-concurrency: ${RABBIT_MQ_MAX_CONCURRENCY:2}
        prefetch: ${RABBIT_MQ_PREFETCH:0}
        retry:
          max-attempts: ${RABBIT_MQ_RETRY_MAX_ATTEMPTS:3}
          enabled: ${RABBIT_MQ_RETRY_ENABLE:true}
          max-interval: ${RABBIT_MQ_RETRY_INTERVAL:10000ms}
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
    ssl: ${REDIS_USE_SSL:false}
    password: ${REDIS_PASSWORD:password}
  datasource:
    url: jdbc:mysql://${MARIADB_HOST:rds}/trak
    username: ${MARIADB_USERNAME:user}
    password: ${MARIADB_PASSWORD:password}

cache:
  duration: ${CACHE_DURATION_SECONDS:300}

api:
  host: ${API_HOST:127.0.0.1}

management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus
