server:
  port: 8080
spring:
  config:
    name: trak-api
  liquibase:
    change-log: classpath:liquibase.sql
  jpa:
    show-sql: true
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
    ssl: ${REDIS_USE_SSL:false}
  datasource:
    url: jdbc:mysql://${MARIADB_HOST:rds}/trak
    data-username: ${MARIADB_USERNAME:user}
    data-password: ${MARIADB_PASSWORD:password}

cache:
  duration: ${CACHE_DURATION_SECONDS:300}

management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus
