apiVersion: v1
data:
  "API_HOST": MTI3LjAuMC4x
  "TOMCAT_PORT": ODA4MA==
  "RABBIT_MQ_USERNAME": dHJhaw==
  "RABBIT_MQ_PASSWORD": cGFzc3dvcmQ=
  "RABBIT_MQ_HOST": cmFiYml0LWlwLXNlcnZpY2U=
  "RABBIT_MQ_VIRTUAL_HOST": Lw==
  "RABBIT_MQ_PORT": NTY3Mg==
  "RABBIT_MQ_CONCURRENCY": Mg==
  "RABBIT_MQ_MAX_CONCURRENCY": Mg==
  "RABBIT_MQ_PREFETCH": MA==
  "RABBIT_MQ_RETRY_MAX_ATTEMPTS": Mw==
  "RABBIT_MQ_RETRY_ENABLE": dHJ1ZQ==
  "RABBIT_MQ_RETRY_INTERVAL": MTAwMDBtcw==
  "REDIS_HOST": cmVkaXMtaXAtc2VydmljZQ==
  "REDIS_PORT": NjM3OQ==
  "REDIS_USE_SSL": ZmFsc2U=
  "REDIS_PASSWORD": cGFzc3dvcmQ=
  "MARIADB_HOST": bWFyaWFkYi1pcC1zZXJ2aWNl
  "MARIADB_USERNAME": dXNlcg==
  "MARIADB_PASSWORD": cGFzc3dvcmQ=
  "CACHE_DURATION_SECONDS": MzAw
kind: Secret
metadata:
  name: api-secrets
  namespace: trak
type: Opaque
