apiVersion: v1
data:
  "RABBITMQ_DEFAULT_USER": dHJhaw==
  "RABBITMQ_DEFAULT_PASS": cGFzc3dvcmQ=
  "RABBITMQ_DEFAULT_VHOST": Lw==
kind: Secret
metadata:
  name: rabbit-secrets
  namespace: trak
type: Opaque
