apiVersion: v1
kind: Service
metadata:
  name: api-ip-service
  namespace: trak
spec:
  type: ClusterIP
  selector:
    component: api
  ports:
    - port: 50051
      targetPort: 50051
      name: grpc
    - port: 8080
      targetPort: 8080
      name: health
