apiVersion: v1
kind: Service
metadata:
  name: rabbit-ip-service
  namespace: trak
spec:
  type: ClusterIP
  selector:
    component: rabbit
  ports:
    - port: 15672
      targetPort: 15672
      name: management
    - port: 5672
      targetPort: 5672
      name: amqp
