apiVersion: v1
kind: Service
metadata:
  name: search-ip-service
  namespace: trak
spec:
  type: ClusterIP
  selector:
    component: search
  ports:
    - port: 50052
      targetPort: 50052
      name: grpc
    - port: 8081
      targetPort: 8081
      name: health
