apiVersion: v1
kind: Service
metadata:
  name: worker-ip-service
  namespace: trak
spec:
  type: ClusterIP
  selector:
    component: worker
  ports:
    - port: 8082
      targetPort: 8082
      name: health
