apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-deployment
  namespace: trak
spec:
  replicas: 1
  selector:
    matchLabels:
      component: search
  template:
    metadata:
      labels:
        component: search
    spec:
      containers:
        - name: search
          image: benjaminslabbert/trak_search:1.0.4-2019-10-24
          ports:
            - containerPort: 50052
              name: grpc
            - containerPort: 8081
              name: health
          env:
            - name: JAVA_OPTS
              value: "-Xmx64m -Xms64m -XX:+TieredCompilation -Xss256k -Xverify:none -XX:+UseG1GC -XX:+UseStringDeduplication -XX:+CMSClassUnloadingEnabled -XshowSettings:vm -XX:NativeMemoryTracking=summary -XX:+UnlockDiagnosticVMOptions -XX:+PrintNMTStatistics -XX:+HeapDumpOnOutOfMemoryError -noverify"
            - name: TOMCAT_PORT
              valueFrom:
                secretKeyRef:
                  key: TOMCAT_PORT
                  name: search-secrets
            - name: RABBIT_MQ_USERNAME
              valueFrom:
                secretKeyRef:
                  key: RABBIT_MQ_USERNAME
                  name: search-secrets
            - name: RABBIT_MQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: RABBIT_MQ_PASSWORD
                  name: search-secrets
            - name: RABBIT_MQ_HOST
              valueFrom:
                secretKeyRef:
                  key: RABBIT_MQ_HOST
                  name: search-secrets
            - name: RABBIT_MQ_VIRTUAL_HOST
              valueFrom:
                secretKeyRef:
                  key: RABBIT_MQ_VIRTUAL_HOST
                  name: search-secrets
            - name: RABBIT_MQ_PORT
              valueFrom:
                secretKeyRef:
                  key: RABBIT_MQ_PORT
                  name: search-secrets
            - name: RABBIT_MQ_CONCURRENCY
              valueFrom:
                secretKeyRef:
                  key: RABBIT_MQ_CONCURRENCY
                  name: search-secrets
            - name: RABBIT_MQ_MAX_CONCURRENCY
              valueFrom:
                secretKeyRef:
                  key: RABBIT_MQ_MAX_CONCURRENCY
                  name: search-secrets
            - name: RABBIT_MQ_PREFETCH
              valueFrom:
                secretKeyRef:
                  key: RABBIT_MQ_PREFETCH
                  name: search-secrets
            - name: RABBIT_MQ_RETRY_MAX_ATTEMPTS
              valueFrom:
                secretKeyRef:
                  key: RABBIT_MQ_RETRY_MAX_ATTEMPTS
                  name: search-secrets
            - name: RABBIT_MQ_RETRY_ENABLE
              valueFrom:
                secretKeyRef:
                  key: RABBIT_MQ_RETRY_ENABLE
                  name: search-secrets
            - name: RABBIT_MQ_RETRY_INTERVAL
              valueFrom:
                secretKeyRef:
                  key: RABBIT_MQ_RETRY_INTERVAL
                  name: search-secrets
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  key: REDIS_HOST
                  name: search-secrets
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  key: REDIS_PORT
                  name: search-secrets
            - name: REDIS_USE_SSL
              valueFrom:
                secretKeyRef:
                  key: REDIS_USE_SSL
                  name: search-secrets
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: REDIS_PASSWORD
                  name: search-secrets
            - name: MARIADB_HOST
              valueFrom:
                secretKeyRef:
                  key: MARIADB_HOST
                  name: search-secrets
            - name: MARIADB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: MARIADB_USERNAME
                  name: search-secrets
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MARIADB_PASSWORD
                  name: search-secrets
            - name: CACHE_DURATION_SECONDS
              valueFrom:
                secretKeyRef:
                  key: CACHE_DURATION_SECONDS
                  name: search-secrets
            - name: SONIC_COMMS_LOG_LEVEL
              valueFrom:
                secretKeyRef:
                  key: SONIC_COMMS_LOG_LEVEL
                  name: search-secrets
            - name: SONIC_HOST
              valueFrom:
                secretKeyRef:
                  key: SONIC_HOST
                  name: search-secrets
            - name: SONIC_PORT
              valueFrom:
                secretKeyRef:
                  key: SONIC_PORT
                  name: search-secrets
            - name: SONIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: SONIC_PASSWORD
                  name: search-secrets
            - name: SONIC_POOL_SIZE
              valueFrom:
                secretKeyRef:
                  key: SONIC_POOL_SIZE
                  name: search-secrets
            - name: SONIC_TIMEOUT_CONN
              valueFrom:
                secretKeyRef:
                  key: SONIC_TIMEOUT_CONN
                  name: search-secrets
            - name: SONIC_TIMEOUT_READ
              valueFrom:
                secretKeyRef:
                  key: SONIC_TIMEOUT_READ
                  name: search-secrets
