server:
  port: 8081
spring:
  config:
    name: trak-search

logging:
  level:
    org.springframework.data.elasticsearch.core: DEBUG

sonic:
  host: 127.0.0.1
  port: 1491
  password: passwd
  pool:
    size: 4
  timeout:
    connection: 5000
    read: 5000

management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus
