server:
  port: 8081
spring:
  config:
    name: trak-search

logging:
  level:
    org.springframework.data.elasticsearch.core: DEBUG

elasticsearch:
  host: localhost
  port: 9300
  clustername: docker-cluster

management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus
