server:
  port: 8081
spring:
  config:
    name: trak-search

logging:
  level:
    org.springframework.data.elasticsearch.core: DEBUG

elasticsearch:
  host: ${ES_HOST:es}
  port: ${ES_PORT:9300}
  clustername: ${ES_CLUSTER_NAME:docker-cluster}

management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus
